title: Playing Sound files with Python
hero_image: images/banner.png
description: How to play sound files with Python
original_url: 
theme: cc-prototype
duration: 1
listed: false
ingredient: true
interests: "sound, music"
technologies: "python"
steps:
  - title: Playing sound files with Python
