---
title: Reproducción de archivos de sonido con Python
hero_image: images/banner.png
description: Cómo reproducir archivos de sonido con Python
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: "sound, music"
technologies: "python"
steps:
  - 
    title: Reproducción de archivos de sonido con Python
